# Generated by Django 5.2 on 2025-04-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armsApp', '0006_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('armsApp.flights',),
        ),
    ]
